// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Game.proto

package com.fuzzjump.server.common.messages.game;

public final class Game {
  private Game() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoadedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.fuzzjump.server.common.messages.game.Loaded)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string gameId = 1;</code>
     */
    boolean hasGameId();
    /**
     * <code>optional string gameId = 1;</code>
     */
    java.lang.String getGameId();
    /**
     * <code>optional string gameId = 1;</code>
     */
    com.google.protobuf.ByteString
        getGameIdBytes();
  }
  /**
   * Protobuf type {@code com.fuzzjump.server.common.messages.game.Loaded}
   */
  public static final class Loaded extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.fuzzjump.server.common.messages.game.Loaded)
      LoadedOrBuilder {
    // Use Loaded.newBuilder() to construct.
    private Loaded(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Loaded(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Loaded defaultInstance;
    public static Loaded getDefaultInstance() {
      return defaultInstance;
    }

    public Loaded getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Loaded(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              gameId_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fuzzjump.server.common.messages.game.Game.internal_static_com_fuzzjump_server_common_messages_game_Loaded_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fuzzjump.server.common.messages.game.Game.internal_static_com_fuzzjump_server_common_messages_game_Loaded_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fuzzjump.server.common.messages.game.Game.Loaded.class, com.fuzzjump.server.common.messages.game.Game.Loaded.Builder.class);
    }

    public static com.google.protobuf.Parser<Loaded> PARSER =
        new com.google.protobuf.AbstractParser<Loaded>() {
      public Loaded parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Loaded(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Loaded> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int GAMEID_FIELD_NUMBER = 1;
    private java.lang.Object gameId_;
    /**
     * <code>optional string gameId = 1;</code>
     */
    public boolean hasGameId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string gameId = 1;</code>
     */
    public java.lang.String getGameId() {
      java.lang.Object ref = gameId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          gameId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string gameId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGameIdBytes() {
      java.lang.Object ref = gameId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      gameId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGameIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGameIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.fuzzjump.server.common.messages.game.Game.Loaded parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuzzjump.server.common.messages.game.Game.Loaded parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuzzjump.server.common.messages.game.Game.Loaded parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuzzjump.server.common.messages.game.Game.Loaded parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuzzjump.server.common.messages.game.Game.Loaded parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fuzzjump.server.common.messages.game.Game.Loaded parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.fuzzjump.server.common.messages.game.Game.Loaded parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.fuzzjump.server.common.messages.game.Game.Loaded parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.fuzzjump.server.common.messages.game.Game.Loaded parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fuzzjump.server.common.messages.game.Game.Loaded parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.fuzzjump.server.common.messages.game.Game.Loaded prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.fuzzjump.server.common.messages.game.Loaded}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.fuzzjump.server.common.messages.game.Loaded)
        com.fuzzjump.server.common.messages.game.Game.LoadedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fuzzjump.server.common.messages.game.Game.internal_static_com_fuzzjump_server_common_messages_game_Loaded_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fuzzjump.server.common.messages.game.Game.internal_static_com_fuzzjump_server_common_messages_game_Loaded_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fuzzjump.server.common.messages.game.Game.Loaded.class, com.fuzzjump.server.common.messages.game.Game.Loaded.Builder.class);
      }

      // Construct using com.fuzzjump.server.common.messages.game.Game.Loaded.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        gameId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fuzzjump.server.common.messages.game.Game.internal_static_com_fuzzjump_server_common_messages_game_Loaded_descriptor;
      }

      public com.fuzzjump.server.common.messages.game.Game.Loaded getDefaultInstanceForType() {
        return com.fuzzjump.server.common.messages.game.Game.Loaded.getDefaultInstance();
      }

      public com.fuzzjump.server.common.messages.game.Game.Loaded build() {
        com.fuzzjump.server.common.messages.game.Game.Loaded result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fuzzjump.server.common.messages.game.Game.Loaded buildPartial() {
        com.fuzzjump.server.common.messages.game.Game.Loaded result = new com.fuzzjump.server.common.messages.game.Game.Loaded(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.gameId_ = gameId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fuzzjump.server.common.messages.game.Game.Loaded) {
          return mergeFrom((com.fuzzjump.server.common.messages.game.Game.Loaded)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fuzzjump.server.common.messages.game.Game.Loaded other) {
        if (other == com.fuzzjump.server.common.messages.game.Game.Loaded.getDefaultInstance()) return this;
        if (other.hasGameId()) {
          bitField0_ |= 0x00000001;
          gameId_ = other.gameId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fuzzjump.server.common.messages.game.Game.Loaded parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fuzzjump.server.common.messages.game.Game.Loaded) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object gameId_ = "";
      /**
       * <code>optional string gameId = 1;</code>
       */
      public boolean hasGameId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string gameId = 1;</code>
       */
      public java.lang.String getGameId() {
        java.lang.Object ref = gameId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            gameId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string gameId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGameIdBytes() {
        java.lang.Object ref = gameId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gameId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string gameId = 1;</code>
       */
      public Builder setGameId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        gameId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string gameId = 1;</code>
       */
      public Builder clearGameId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        gameId_ = getDefaultInstance().getGameId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string gameId = 1;</code>
       */
      public Builder setGameIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        gameId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.fuzzjump.server.common.messages.game.Loaded)
    }

    static {
      defaultInstance = new Loaded(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.fuzzjump.server.common.messages.game.Loaded)
  }

  public interface LoadedResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.fuzzjump.server.common.messages.game.LoadedResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool found = 1;</code>
     */
    boolean hasFound();
    /**
     * <code>optional bool found = 1;</code>
     */
    boolean getFound();
  }
  /**
   * Protobuf type {@code com.fuzzjump.server.common.messages.game.LoadedResponse}
   */
  public static final class LoadedResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.fuzzjump.server.common.messages.game.LoadedResponse)
      LoadedResponseOrBuilder {
    // Use LoadedResponse.newBuilder() to construct.
    private LoadedResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoadedResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoadedResponse defaultInstance;
    public static LoadedResponse getDefaultInstance() {
      return defaultInstance;
    }

    public LoadedResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoadedResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              found_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fuzzjump.server.common.messages.game.Game.internal_static_com_fuzzjump_server_common_messages_game_LoadedResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fuzzjump.server.common.messages.game.Game.internal_static_com_fuzzjump_server_common_messages_game_LoadedResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fuzzjump.server.common.messages.game.Game.LoadedResponse.class, com.fuzzjump.server.common.messages.game.Game.LoadedResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<LoadedResponse> PARSER =
        new com.google.protobuf.AbstractParser<LoadedResponse>() {
      public LoadedResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoadedResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoadedResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FOUND_FIELD_NUMBER = 1;
    private boolean found_;
    /**
     * <code>optional bool found = 1;</code>
     */
    public boolean hasFound() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool found = 1;</code>
     */
    public boolean getFound() {
      return found_;
    }

    private void initFields() {
      found_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, found_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, found_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.fuzzjump.server.common.messages.game.Game.LoadedResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuzzjump.server.common.messages.game.Game.LoadedResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuzzjump.server.common.messages.game.Game.LoadedResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuzzjump.server.common.messages.game.Game.LoadedResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuzzjump.server.common.messages.game.Game.LoadedResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fuzzjump.server.common.messages.game.Game.LoadedResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.fuzzjump.server.common.messages.game.Game.LoadedResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.fuzzjump.server.common.messages.game.Game.LoadedResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.fuzzjump.server.common.messages.game.Game.LoadedResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fuzzjump.server.common.messages.game.Game.LoadedResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.fuzzjump.server.common.messages.game.Game.LoadedResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.fuzzjump.server.common.messages.game.LoadedResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.fuzzjump.server.common.messages.game.LoadedResponse)
        com.fuzzjump.server.common.messages.game.Game.LoadedResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fuzzjump.server.common.messages.game.Game.internal_static_com_fuzzjump_server_common_messages_game_LoadedResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fuzzjump.server.common.messages.game.Game.internal_static_com_fuzzjump_server_common_messages_game_LoadedResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fuzzjump.server.common.messages.game.Game.LoadedResponse.class, com.fuzzjump.server.common.messages.game.Game.LoadedResponse.Builder.class);
      }

      // Construct using com.fuzzjump.server.common.messages.game.Game.LoadedResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        found_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fuzzjump.server.common.messages.game.Game.internal_static_com_fuzzjump_server_common_messages_game_LoadedResponse_descriptor;
      }

      public com.fuzzjump.server.common.messages.game.Game.LoadedResponse getDefaultInstanceForType() {
        return com.fuzzjump.server.common.messages.game.Game.LoadedResponse.getDefaultInstance();
      }

      public com.fuzzjump.server.common.messages.game.Game.LoadedResponse build() {
        com.fuzzjump.server.common.messages.game.Game.LoadedResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fuzzjump.server.common.messages.game.Game.LoadedResponse buildPartial() {
        com.fuzzjump.server.common.messages.game.Game.LoadedResponse result = new com.fuzzjump.server.common.messages.game.Game.LoadedResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.found_ = found_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fuzzjump.server.common.messages.game.Game.LoadedResponse) {
          return mergeFrom((com.fuzzjump.server.common.messages.game.Game.LoadedResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fuzzjump.server.common.messages.game.Game.LoadedResponse other) {
        if (other == com.fuzzjump.server.common.messages.game.Game.LoadedResponse.getDefaultInstance()) return this;
        if (other.hasFound()) {
          setFound(other.getFound());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fuzzjump.server.common.messages.game.Game.LoadedResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fuzzjump.server.common.messages.game.Game.LoadedResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean found_ ;
      /**
       * <code>optional bool found = 1;</code>
       */
      public boolean hasFound() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool found = 1;</code>
       */
      public boolean getFound() {
        return found_;
      }
      /**
       * <code>optional bool found = 1;</code>
       */
      public Builder setFound(boolean value) {
        bitField0_ |= 0x00000001;
        found_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool found = 1;</code>
       */
      public Builder clearFound() {
        bitField0_ = (bitField0_ & ~0x00000001);
        found_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.fuzzjump.server.common.messages.game.LoadedResponse)
    }

    static {
      defaultInstance = new LoadedResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.fuzzjump.server.common.messages.game.LoadedResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fuzzjump_server_common_messages_game_Loaded_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_fuzzjump_server_common_messages_game_Loaded_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fuzzjump_server_common_messages_game_LoadedResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_fuzzjump_server_common_messages_game_LoadedResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nGame.proto\022(com.fuzzjump.server.common" +
      ".messages.game\"\030\n\006Loaded\022\016\n\006gameId\030\001 \001(\t" +
      "\"\037\n\016LoadedResponse\022\r\n\005found\030\001 \001(\010B*\n(com" +
      ".fuzzjump.server.common.messages.game"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_fuzzjump_server_common_messages_game_Loaded_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_fuzzjump_server_common_messages_game_Loaded_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_fuzzjump_server_common_messages_game_Loaded_descriptor,
        new java.lang.String[] { "GameId", });
    internal_static_com_fuzzjump_server_common_messages_game_LoadedResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_fuzzjump_server_common_messages_game_LoadedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_fuzzjump_server_common_messages_game_LoadedResponse_descriptor,
        new java.lang.String[] { "Found", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
