package com.fuzzjump.server.game;


import com.fuzzjump.server.base.FuzzJumpPlayer;
import com.fuzzjump.server.common.messages.join.Join;
import com.steveadoo.server.base.Player;
import com.steveadoo.server.base.validation.Validator;
import com.steveadoo.server.common.packets.Validation;

import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.Iterator;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.TimeUnit;

public class GameServerPlayerValidator implements Validator {

    private static final long PURGE_RATE = 5000;
    private static final long KEY_DURATION = 30000;

    private final GameServer gameServer;

    private ConcurrentHashMap<String, Long> sessionKeys = new ConcurrentHashMap<>();

    public GameServerPlayerValidator(GameServer gameServer) {
        this.gameServer = gameServer;
    }

    @Override
    public void init() {
        this.gameServer.getExecutorService().scheduleAtFixedRate(this::purgeOldKeys, 0, PURGE_RATE, TimeUnit.MILLISECONDS);
    }

    /**
     * Removes old session keys from the map (eg someone fails to make a connection to the game
     */
    private void purgeOldKeys() {
        Iterator<Map.Entry<String, Long>> entries = sessionKeys.entrySet().iterator();
        while(entries.hasNext()) {
            Map.Entry<String, Long> entry = entries.next();
            long time = entry.getValue();
            if (System.currentTimeMillis() - time > KEY_DURATION) {
                entries.remove();
            }
        }
    }

    @Override
    public boolean matches(Class<?> clazz, Object message) {
        return clazz == Join.JoinPacket.class && ((Join.JoinPacket) message).hasServerSessionKey();
    }

    /**
     * The game server only lets you connect w/ game server session keys(eg, not keys generated by the web api).
     */
    @Override
    public CompletableFuture<Boolean> validate(Player player, Object message) {
        FuzzJumpPlayer fuzzJumpPlayer = (FuzzJumpPlayer) player;
        Join.JoinPacket joinPacket = (Join.JoinPacket) message;
        if (!sessionKeys.containsKey(joinPacket.getServerSessionKey())) {
            player.getChannel().writeAndFlush(getJoinResponse(false));
            return CompletableFuture.completedFuture(false);
        }
        fuzzJumpPlayer.setUserId(joinPacket.getUserId());
        sessionKeys.remove(joinPacket.getServerSessionKey());
        player.getChannel().writeAndFlush(getJoinResponse(true));
        return CompletableFuture.completedFuture(true);
    }

    /**
     * Generates and stores sessionKeys for joining this server
     * TODO should we attach profile id to this?
     */
    public String[] generateSessionKeys(int keyCount) {
        String[] keys = new String[keyCount];
        for(int i = 0; i < keyCount; i++) {
            String key = gameServer.generateKey();
            keys[i] = key;
            sessionKeys.put(key, System.currentTimeMillis());
        }
        return keys;
    }

    private Join.JoinResponsePacket getJoinResponse(boolean valid) {
        return Join.JoinResponsePacket.newBuilder()
                .setRedirect(false)
                .setServerIp(gameServer.getServerInfo().ip)
                .setServerPort(gameServer.getServerInfo().port)
                .setStatus(valid ? Validation.AUTHORIZED : Validation.UNAUTHORIZED)
                .build();
    }

}
