// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Join.proto

package com.fuzzjump.server.common.messages.join;

public final class Join {
  private Join() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface JoinPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.steveadoo.server.common.JoinPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1;</code>
     */
    int getVersion();

    /**
     * <code>optional string userId = 2;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional string userId = 2;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>optional string userId = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>optional string sessionKey = 3;</code>
     */
    boolean hasSessionKey();
    /**
     * <code>optional string sessionKey = 3;</code>
     */
    java.lang.String getSessionKey();
    /**
     * <code>optional string sessionKey = 3;</code>
     */
    com.google.protobuf.ByteString
        getSessionKeyBytes();

    /**
     * <code>optional string serverSessionKey = 4;</code>
     */
    boolean hasServerSessionKey();
    /**
     * <code>optional string serverSessionKey = 4;</code>
     */
    java.lang.String getServerSessionKey();
    /**
     * <code>optional string serverSessionKey = 4;</code>
     */
    com.google.protobuf.ByteString
        getServerSessionKeyBytes();
  }
  /**
   * Protobuf type {@code com.steveadoo.server.common.JoinPacket}
   */
  public static final class JoinPacket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.steveadoo.server.common.JoinPacket)
      JoinPacketOrBuilder {
    // Use JoinPacket.newBuilder() to construct.
    private JoinPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private JoinPacket(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final JoinPacket defaultInstance;
    public static JoinPacket getDefaultInstance() {
      return defaultInstance;
    }

    public JoinPacket getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private JoinPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              userId_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              sessionKey_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              serverSessionKey_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fuzzjump.server.common.messages.join.Join.internal_static_com_steveadoo_server_common_JoinPacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fuzzjump.server.common.messages.join.Join.internal_static_com_steveadoo_server_common_JoinPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fuzzjump.server.common.messages.join.Join.JoinPacket.class, com.fuzzjump.server.common.messages.join.Join.JoinPacket.Builder.class);
    }

    public static com.google.protobuf.Parser<JoinPacket> PARSER =
        new com.google.protobuf.AbstractParser<JoinPacket>() {
      public JoinPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JoinPacket(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<JoinPacket> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private java.lang.Object userId_;
    /**
     * <code>optional string userId = 2;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string userId = 2;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SESSIONKEY_FIELD_NUMBER = 3;
    private java.lang.Object sessionKey_;
    /**
     * <code>optional string sessionKey = 3;</code>
     */
    public boolean hasSessionKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string sessionKey = 3;</code>
     */
    public java.lang.String getSessionKey() {
      java.lang.Object ref = sessionKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sessionKey = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSessionKeyBytes() {
      java.lang.Object ref = sessionKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERSESSIONKEY_FIELD_NUMBER = 4;
    private java.lang.Object serverSessionKey_;
    /**
     * <code>optional string serverSessionKey = 4;</code>
     */
    public boolean hasServerSessionKey() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string serverSessionKey = 4;</code>
     */
    public java.lang.String getServerSessionKey() {
      java.lang.Object ref = serverSessionKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serverSessionKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string serverSessionKey = 4;</code>
     */
    public com.google.protobuf.ByteString
        getServerSessionKeyBytes() {
      java.lang.Object ref = serverSessionKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverSessionKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      version_ = 0;
      userId_ = "";
      sessionKey_ = "";
      serverSessionKey_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSessionKeyBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getServerSessionKeyBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSessionKeyBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getServerSessionKeyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.fuzzjump.server.common.messages.join.Join.JoinPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuzzjump.server.common.messages.join.Join.JoinPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuzzjump.server.common.messages.join.Join.JoinPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuzzjump.server.common.messages.join.Join.JoinPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuzzjump.server.common.messages.join.Join.JoinPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fuzzjump.server.common.messages.join.Join.JoinPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.fuzzjump.server.common.messages.join.Join.JoinPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.fuzzjump.server.common.messages.join.Join.JoinPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.fuzzjump.server.common.messages.join.Join.JoinPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fuzzjump.server.common.messages.join.Join.JoinPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.fuzzjump.server.common.messages.join.Join.JoinPacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.steveadoo.server.common.JoinPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.steveadoo.server.common.JoinPacket)
        com.fuzzjump.server.common.messages.join.Join.JoinPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fuzzjump.server.common.messages.join.Join.internal_static_com_steveadoo_server_common_JoinPacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fuzzjump.server.common.messages.join.Join.internal_static_com_steveadoo_server_common_JoinPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fuzzjump.server.common.messages.join.Join.JoinPacket.class, com.fuzzjump.server.common.messages.join.Join.JoinPacket.Builder.class);
      }

      // Construct using com.fuzzjump.server.common.messages.join.Join.JoinPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        serverSessionKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fuzzjump.server.common.messages.join.Join.internal_static_com_steveadoo_server_common_JoinPacket_descriptor;
      }

      public com.fuzzjump.server.common.messages.join.Join.JoinPacket getDefaultInstanceForType() {
        return com.fuzzjump.server.common.messages.join.Join.JoinPacket.getDefaultInstance();
      }

      public com.fuzzjump.server.common.messages.join.Join.JoinPacket build() {
        com.fuzzjump.server.common.messages.join.Join.JoinPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fuzzjump.server.common.messages.join.Join.JoinPacket buildPartial() {
        com.fuzzjump.server.common.messages.join.Join.JoinPacket result = new com.fuzzjump.server.common.messages.join.Join.JoinPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sessionKey_ = sessionKey_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.serverSessionKey_ = serverSessionKey_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fuzzjump.server.common.messages.join.Join.JoinPacket) {
          return mergeFrom((com.fuzzjump.server.common.messages.join.Join.JoinPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fuzzjump.server.common.messages.join.Join.JoinPacket other) {
        if (other == com.fuzzjump.server.common.messages.join.Join.JoinPacket.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasUserId()) {
          bitField0_ |= 0x00000002;
          userId_ = other.userId_;
          onChanged();
        }
        if (other.hasSessionKey()) {
          bitField0_ |= 0x00000004;
          sessionKey_ = other.sessionKey_;
          onChanged();
        }
        if (other.hasServerSessionKey()) {
          bitField0_ |= 0x00000008;
          serverSessionKey_ = other.serverSessionKey_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fuzzjump.server.common.messages.join.Join.JoinPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fuzzjump.server.common.messages.join.Join.JoinPacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <code>required int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>optional string userId = 2;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sessionKey_ = "";
      /**
       * <code>optional string sessionKey = 3;</code>
       */
      public boolean hasSessionKey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string sessionKey = 3;</code>
       */
      public java.lang.String getSessionKey() {
        java.lang.Object ref = sessionKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sessionKey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sessionKey = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSessionKeyBytes() {
        java.lang.Object ref = sessionKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sessionKey = 3;</code>
       */
      public Builder setSessionKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sessionKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionKey = 3;</code>
       */
      public Builder clearSessionKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sessionKey_ = getDefaultInstance().getSessionKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionKey = 3;</code>
       */
      public Builder setSessionKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sessionKey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object serverSessionKey_ = "";
      /**
       * <code>optional string serverSessionKey = 4;</code>
       */
      public boolean hasServerSessionKey() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string serverSessionKey = 4;</code>
       */
      public java.lang.String getServerSessionKey() {
        java.lang.Object ref = serverSessionKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serverSessionKey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string serverSessionKey = 4;</code>
       */
      public com.google.protobuf.ByteString
          getServerSessionKeyBytes() {
        java.lang.Object ref = serverSessionKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverSessionKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string serverSessionKey = 4;</code>
       */
      public Builder setServerSessionKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        serverSessionKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string serverSessionKey = 4;</code>
       */
      public Builder clearServerSessionKey() {
        bitField0_ = (bitField0_ & ~0x00000008);
        serverSessionKey_ = getDefaultInstance().getServerSessionKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string serverSessionKey = 4;</code>
       */
      public Builder setServerSessionKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        serverSessionKey_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.steveadoo.server.common.JoinPacket)
    }

    static {
      defaultInstance = new JoinPacket(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.steveadoo.server.common.JoinPacket)
  }

  public interface JoinResponsePacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.steveadoo.server.common.JoinResponsePacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string serverIp = 1;</code>
     */
    boolean hasServerIp();
    /**
     * <code>optional string serverIp = 1;</code>
     */
    java.lang.String getServerIp();
    /**
     * <code>optional string serverIp = 1;</code>
     */
    com.google.protobuf.ByteString
        getServerIpBytes();

    /**
     * <code>optional int32 serverPort = 2;</code>
     */
    boolean hasServerPort();
    /**
     * <code>optional int32 serverPort = 2;</code>
     */
    int getServerPort();

    /**
     * <code>required int32 status = 3;</code>
     */
    boolean hasStatus();
    /**
     * <code>required int32 status = 3;</code>
     */
    int getStatus();

    /**
     * <code>optional string serverSessionKey = 4;</code>
     */
    boolean hasServerSessionKey();
    /**
     * <code>optional string serverSessionKey = 4;</code>
     */
    java.lang.String getServerSessionKey();
    /**
     * <code>optional string serverSessionKey = 4;</code>
     */
    com.google.protobuf.ByteString
        getServerSessionKeyBytes();

    /**
     * <code>required bool redirect = 5;</code>
     */
    boolean hasRedirect();
    /**
     * <code>required bool redirect = 5;</code>
     */
    boolean getRedirect();
  }
  /**
   * Protobuf type {@code com.steveadoo.server.common.JoinResponsePacket}
   */
  public static final class JoinResponsePacket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.steveadoo.server.common.JoinResponsePacket)
      JoinResponsePacketOrBuilder {
    // Use JoinResponsePacket.newBuilder() to construct.
    private JoinResponsePacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private JoinResponsePacket(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final JoinResponsePacket defaultInstance;
    public static JoinResponsePacket getDefaultInstance() {
      return defaultInstance;
    }

    public JoinResponsePacket getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private JoinResponsePacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              serverIp_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              serverPort_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              status_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              serverSessionKey_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              redirect_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fuzzjump.server.common.messages.join.Join.internal_static_com_steveadoo_server_common_JoinResponsePacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fuzzjump.server.common.messages.join.Join.internal_static_com_steveadoo_server_common_JoinResponsePacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket.class, com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket.Builder.class);
    }

    public static com.google.protobuf.Parser<JoinResponsePacket> PARSER =
        new com.google.protobuf.AbstractParser<JoinResponsePacket>() {
      public JoinResponsePacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JoinResponsePacket(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<JoinResponsePacket> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SERVERIP_FIELD_NUMBER = 1;
    private java.lang.Object serverIp_;
    /**
     * <code>optional string serverIp = 1;</code>
     */
    public boolean hasServerIp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string serverIp = 1;</code>
     */
    public java.lang.String getServerIp() {
      java.lang.Object ref = serverIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serverIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string serverIp = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServerIpBytes() {
      java.lang.Object ref = serverIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERPORT_FIELD_NUMBER = 2;
    private int serverPort_;
    /**
     * <code>optional int32 serverPort = 2;</code>
     */
    public boolean hasServerPort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 serverPort = 2;</code>
     */
    public int getServerPort() {
      return serverPort_;
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private int status_;
    /**
     * <code>required int32 status = 3;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 status = 3;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int SERVERSESSIONKEY_FIELD_NUMBER = 4;
    private java.lang.Object serverSessionKey_;
    /**
     * <code>optional string serverSessionKey = 4;</code>
     */
    public boolean hasServerSessionKey() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string serverSessionKey = 4;</code>
     */
    public java.lang.String getServerSessionKey() {
      java.lang.Object ref = serverSessionKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serverSessionKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string serverSessionKey = 4;</code>
     */
    public com.google.protobuf.ByteString
        getServerSessionKeyBytes() {
      java.lang.Object ref = serverSessionKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverSessionKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REDIRECT_FIELD_NUMBER = 5;
    private boolean redirect_;
    /**
     * <code>required bool redirect = 5;</code>
     */
    public boolean hasRedirect() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bool redirect = 5;</code>
     */
    public boolean getRedirect() {
      return redirect_;
    }

    private void initFields() {
      serverIp_ = "";
      serverPort_ = 0;
      status_ = 0;
      serverSessionKey_ = "";
      redirect_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRedirect()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getServerIpBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, serverPort_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, status_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getServerSessionKeyBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, redirect_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getServerIpBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, serverPort_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, status_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getServerSessionKeyBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, redirect_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.steveadoo.server.common.JoinResponsePacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.steveadoo.server.common.JoinResponsePacket)
        com.fuzzjump.server.common.messages.join.Join.JoinResponsePacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fuzzjump.server.common.messages.join.Join.internal_static_com_steveadoo_server_common_JoinResponsePacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fuzzjump.server.common.messages.join.Join.internal_static_com_steveadoo_server_common_JoinResponsePacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket.class, com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket.Builder.class);
      }

      // Construct using com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serverIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        serverPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        serverSessionKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        redirect_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fuzzjump.server.common.messages.join.Join.internal_static_com_steveadoo_server_common_JoinResponsePacket_descriptor;
      }

      public com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket getDefaultInstanceForType() {
        return com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket.getDefaultInstance();
      }

      public com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket build() {
        com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket buildPartial() {
        com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket result = new com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverIp_ = serverIp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.serverPort_ = serverPort_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.serverSessionKey_ = serverSessionKey_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.redirect_ = redirect_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket) {
          return mergeFrom((com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket other) {
        if (other == com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket.getDefaultInstance()) return this;
        if (other.hasServerIp()) {
          bitField0_ |= 0x00000001;
          serverIp_ = other.serverIp_;
          onChanged();
        }
        if (other.hasServerPort()) {
          setServerPort(other.getServerPort());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasServerSessionKey()) {
          bitField0_ |= 0x00000008;
          serverSessionKey_ = other.serverSessionKey_;
          onChanged();
        }
        if (other.hasRedirect()) {
          setRedirect(other.getRedirect());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStatus()) {
          
          return false;
        }
        if (!hasRedirect()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fuzzjump.server.common.messages.join.Join.JoinResponsePacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object serverIp_ = "";
      /**
       * <code>optional string serverIp = 1;</code>
       */
      public boolean hasServerIp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string serverIp = 1;</code>
       */
      public java.lang.String getServerIp() {
        java.lang.Object ref = serverIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serverIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string serverIp = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServerIpBytes() {
        java.lang.Object ref = serverIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string serverIp = 1;</code>
       */
      public Builder setServerIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serverIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string serverIp = 1;</code>
       */
      public Builder clearServerIp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverIp_ = getDefaultInstance().getServerIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string serverIp = 1;</code>
       */
      public Builder setServerIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serverIp_ = value;
        onChanged();
        return this;
      }

      private int serverPort_ ;
      /**
       * <code>optional int32 serverPort = 2;</code>
       */
      public boolean hasServerPort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 serverPort = 2;</code>
       */
      public int getServerPort() {
        return serverPort_;
      }
      /**
       * <code>optional int32 serverPort = 2;</code>
       */
      public Builder setServerPort(int value) {
        bitField0_ |= 0x00000002;
        serverPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 serverPort = 2;</code>
       */
      public Builder clearServerPort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serverPort_ = 0;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>required int32 status = 3;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 status = 3;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>required int32 status = 3;</code>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000004;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 status = 3;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object serverSessionKey_ = "";
      /**
       * <code>optional string serverSessionKey = 4;</code>
       */
      public boolean hasServerSessionKey() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string serverSessionKey = 4;</code>
       */
      public java.lang.String getServerSessionKey() {
        java.lang.Object ref = serverSessionKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serverSessionKey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string serverSessionKey = 4;</code>
       */
      public com.google.protobuf.ByteString
          getServerSessionKeyBytes() {
        java.lang.Object ref = serverSessionKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverSessionKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string serverSessionKey = 4;</code>
       */
      public Builder setServerSessionKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        serverSessionKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string serverSessionKey = 4;</code>
       */
      public Builder clearServerSessionKey() {
        bitField0_ = (bitField0_ & ~0x00000008);
        serverSessionKey_ = getDefaultInstance().getServerSessionKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string serverSessionKey = 4;</code>
       */
      public Builder setServerSessionKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        serverSessionKey_ = value;
        onChanged();
        return this;
      }

      private boolean redirect_ ;
      /**
       * <code>required bool redirect = 5;</code>
       */
      public boolean hasRedirect() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bool redirect = 5;</code>
       */
      public boolean getRedirect() {
        return redirect_;
      }
      /**
       * <code>required bool redirect = 5;</code>
       */
      public Builder setRedirect(boolean value) {
        bitField0_ |= 0x00000010;
        redirect_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool redirect = 5;</code>
       */
      public Builder clearRedirect() {
        bitField0_ = (bitField0_ & ~0x00000010);
        redirect_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.steveadoo.server.common.JoinResponsePacket)
    }

    static {
      defaultInstance = new JoinResponsePacket(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.steveadoo.server.common.JoinResponsePacket)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_steveadoo_server_common_JoinPacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_steveadoo_server_common_JoinPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_steveadoo_server_common_JoinResponsePacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_steveadoo_server_common_JoinResponsePacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nJoin.proto\022\033com.steveadoo.server.commo" +
      "n\"[\n\nJoinPacket\022\017\n\007version\030\001 \002(\005\022\016\n\006user" +
      "Id\030\002 \001(\t\022\022\n\nsessionKey\030\003 \001(\t\022\030\n\020serverSe" +
      "ssionKey\030\004 \001(\t\"v\n\022JoinResponsePacket\022\020\n\010" +
      "serverIp\030\001 \001(\t\022\022\n\nserverPort\030\002 \001(\005\022\016\n\006st" +
      "atus\030\003 \002(\005\022\030\n\020serverSessionKey\030\004 \001(\t\022\020\n\010" +
      "redirect\030\005 \002(\010B*\n(com.fuzzjump.server.co" +
      "mmon.messages.join"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_steveadoo_server_common_JoinPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_steveadoo_server_common_JoinPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_steveadoo_server_common_JoinPacket_descriptor,
        new java.lang.String[] { "Version", "UserId", "SessionKey", "ServerSessionKey", });
    internal_static_com_steveadoo_server_common_JoinResponsePacket_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_steveadoo_server_common_JoinResponsePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_steveadoo_server_common_JoinResponsePacket_descriptor,
        new java.lang.String[] { "ServerIp", "ServerPort", "Status", "ServerSessionKey", "Redirect", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
